# Generated by Django 6.0.6 on 2026-08-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_can_add_projects_profile_can_delete_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_add_projects',
            new_name='can_add',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_delete_projects',
            new_name='can_delete',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_edit_projects',
            new_name='can_edit',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_view_projects',
            new_name='can_view',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_manage_users',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
