# Generated by Django 6.0.6 on 2026-08-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_can_add_projects_profile_can_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
