# Generated by Django 6.0.6 on 2026-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_add',
            new_name='can_add_students',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_delete',
            new_name='can_delete_students',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_edit',
            new_name='can_edit_students',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_view',
            new_name='can_view_students',
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_grades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
