# Generated by Django 6.0.6 on 2026-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_can_add_profile_can_add_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
