# Generated by Django 6.0.6 on 2026-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_can_manage_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_subjects',
            field=models.BooleanField(default=True),
        ),
    ]
