# Generated by Django 6.0.6 on 2026-08-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_can_view_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_grades',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Manager', 'Manager'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
