# Generated by Django 6.0.6 on 2026-08-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_can_view_attendance_profile_can_view_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_teachers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_teachers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_users',
            field=models.BooleanField(default=False),
        ),
    ]
