# Generated by Django 6.0.6 on 2026-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_can_manage_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_view_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_view_subjects',
            field=models.BooleanField(default=False),
        ),
    ]
