# Generated by Django 6.0.6 on 2026-08-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_can_view_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
