# Generated by Django 6.0.6 on 2026-08-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_can_view_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_view_enrollment',
        ),
    ]
