# Generated by Django 6.0.6 on 2026-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
