# Generated by Django 6.0.6 on 2026-08-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='account_password',
        ),
        migrations.AddField(
            model_name='student',
            name='temporary_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
