# Generated by Django 6.0.6 on 2026-08-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['subject__name']},
        ),
    ]
