# ============================================================
# STUDENTS MODELS
# ============================================================
#
# Student Management System
#
# Contains:
#
# 1. ClassRoom
# 2. Student
# 3. ClassSubject
#
# Student Account:
#
# Student
#     ↓
# Django User
#     ↓
# Username = Student ID
#
# Student ID:
#
#     Automatically generated by the system
#
# Examples:
#
#     STU001
#     STU002
#     STU003
#
# Temporary password:
#
# Student.temporary_password
#
# IMPORTANT:
#
# Django User password is stored using Django's
# secure password hashing.
#
# ============================================================


# ============================================================
# IMPORTS
# ============================================================

from django.db import models

from django.contrib.auth.models import User


# ============================================================
# CLASS ROOM MODEL
# ============================================================

class ClassRoom(models.Model):

    # ========================================================
    # CLASS NAME
    # ========================================================

    name = models.CharField(
        max_length=100,
        unique=True,
    )

    # ========================================================
    # DESCRIPTION
    # ========================================================

    description = models.TextField(
        blank=True,
    )

    # ========================================================
    # STATUS
    # ========================================================

    STATUS_CHOICES = (
        ("Active", "Active"),
        ("Inactive", "Inactive"),
    )

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="Active",
    )

    # ========================================================
    # CREATED AT
    # ========================================================

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    # ========================================================
    # UPDATED AT
    # ========================================================

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    # ========================================================
    # STRING REPRESENTATION
    # ========================================================

    def __str__(self):
        return self.name

    # ========================================================
    # META
    # ========================================================

    class Meta:
        ordering = [
            "name",
        ]

        verbose_name = "Class"

        verbose_name_plural = "Classes"


# ============================================================
# STUDENT MODEL
# ============================================================

class Student(models.Model):

    # ========================================================
    # DJANGO USER ACCOUNT
    # ========================================================
    #
    # Links the Student record to Django authentication.
    #
    # Example:
    #
    # Student:
    #     STU001
    #
    # Django User:
    #     username = STU001
    #
    # SET_NULL means:
    #
    # If the Django User is deleted,
    # the Student record remains.
    #
    # ========================================================

    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="student_profile",
    )

    # ========================================================
    # CLASS
    # ========================================================

    class_room = models.ForeignKey(
        ClassRoom,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="students",
    )

    # ========================================================
    # STUDENT ID
    # ========================================================
    #
    # IMPORTANT:
    #
    # The administrator does NOT enter the Student ID.
    #
    # The system automatically generates:
    #
    #     STU001
    #     STU002
    #     STU003
    #     STU004
    #
    # The number is based on the highest existing
    # STU number + 1.
    #
    # Example:
    #
    # Existing:
    #
    #     STU001
    #     STU002
    #     STU003
    #
    # New student:
    #
    #     STU004
    #
    # ========================================================

    student_id = models.CharField(
        max_length=20,
        unique=True,
        blank=True,
    )

    # ========================================================
    # FIRST NAME
    # ========================================================

    first_name = models.CharField(
        max_length=100,
    )

    # ========================================================
    # LAST NAME
    # ========================================================

    last_name = models.CharField(
        max_length=100,
    )

    # ========================================================
    # EMAIL
    # ========================================================

    email = models.EmailField(
        unique=True,
    )

    # ========================================================
    # PHONE
    # ========================================================

    phone = models.CharField(
        max_length=20,
        blank=True,
    )

    # ========================================================
    # GENDER
    # ========================================================

    GENDER_CHOICES = (
        ("Male", "Male"),
        ("Female", "Female"),
    )

    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
    )

    # ========================================================
    # DATE OF BIRTH
    # ========================================================

    date_of_birth = models.DateField()

    # ========================================================
    # ADDRESS
    # ========================================================

    address = models.TextField(
        blank=True,
    )

    # ========================================================
    # TEMPORARY PASSWORD
    # ========================================================
    #
    # System can store the temporary credential here
    # according to the existing project workflow.
    #
    # ========================================================

    temporary_password = models.CharField(
        max_length=128,
        blank=True,
        default="",
    )

    # ========================================================
    # CREATED AT
    # ========================================================

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    # ========================================================
    # UPDATED AT
    # ========================================================

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    # ========================================================
    # AUTOMATIC STUDENT ID GENERATOR
    # ========================================================

    def generate_student_id(self):
        """
        Generate the next sequential Student ID.

        Format:

            STU001
            STU002
            STU003
            ...

        Existing Student IDs that do not follow the
        STU<number> pattern are ignored.
        """

        # ----------------------------------------------------
        # GET EXISTING IDS
        # ----------------------------------------------------

        existing_ids = (
            Student.objects
            .exclude(
                student_id=""
            )
            .values_list(
                "student_id",
                flat=True,
            )
        )

        # ----------------------------------------------------
        # FIND HIGHEST NUMBER
        # ----------------------------------------------------

        highest_number = 0

        for existing_id in existing_ids:

            if not existing_id:
                continue

            existing_id = str(
                existing_id
            ).strip().upper()

            # Expected format:
            #
            # STU001

            if not existing_id.startswith(
                "STU"
            ):
                continue

            number_part = (
                existing_id[3:]
            )

            if not number_part.isdigit():
                continue

            number = int(
                number_part
            )

            if number > highest_number:
                highest_number = number

        # ----------------------------------------------------
        # NEXT NUMBER
        # ----------------------------------------------------

        next_number = (
            highest_number + 1
        )

        # ----------------------------------------------------
        # BUILD ID
        # ----------------------------------------------------

        generated_id = (
            f"STU{next_number:03d}"
        )

        # ----------------------------------------------------
        # SAFETY CHECK
        # ----------------------------------------------------

        while (
            Student.objects
            .filter(
                student_id=generated_id
            )
            .exclude(
                pk=self.pk
            )
            .exists()
        ):

            next_number += 1

            generated_id = (
                f"STU{next_number:03d}"
            )

        return generated_id

    # ========================================================
    # SAVE
    # ========================================================

    def save(
        self,
        *args,
        **kwargs,
    ):
        """
        Automatically assign Student ID when creating
        a new Student.

        Existing Student IDs are preserved.
        """

        # ----------------------------------------------------
        # NEW STUDENT
        # ----------------------------------------------------

        if not self.student_id:

            self.student_id = (
                self.generate_student_id()
            )

        # ----------------------------------------------------
        # SAVE
        # ----------------------------------------------------

        super().save(
            *args,
            **kwargs
        )

    # ========================================================
    # FULL NAME PROPERTY
    # ========================================================

    @property
    def full_name(self):

        return (
            f"{self.first_name} "
            f"{self.last_name}"
        )

    # ========================================================
    # STRING REPRESENTATION
    # ========================================================

    def __str__(self):

        return (
            f"{self.student_id} - "
            f"{self.first_name} "
            f"{self.last_name}"
        )

    # ========================================================
    # META
    # ========================================================

    class Meta:

        ordering = [
            "first_name",
            "last_name",
        ]

        verbose_name = "Student"

        verbose_name_plural = "Students"


# ============================================================
# CLASS SUBJECT / CLASS CURRICULUM MODEL
# ============================================================
#
# Connects:
#
#     ClassRoom <----> Subject
#
# Example:
#
# Grade 7A
#     -> Mathematics
#     -> English
#     -> Science
#
# Grade 8A
#     -> Mathematics
#     -> English
#     -> Biology
#
# This is the official class curriculum assignment.
#
# ============================================================

class ClassSubject(models.Model):

    # ========================================================
    # CLASS
    # ========================================================

    class_room = models.ForeignKey(
        ClassRoom,
        on_delete=models.CASCADE,
        related_name="class_subjects",
    )

    # ========================================================
    # SUBJECT
    # ========================================================

    subject = models.ForeignKey(
        "subjects.Subject",
        on_delete=models.CASCADE,
        related_name="class_assignments",
    )

    # ========================================================
    # STATUS
    # ========================================================

    STATUS_CHOICES = (
        ("Active", "Active"),
        ("Inactive", "Inactive"),
    )

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="Active",
    )

    # ========================================================
    # CREATED AT
    # ========================================================

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    # ========================================================
    # UPDATED AT
    # ========================================================

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    # ========================================================
    # STRING REPRESENTATION
    # ========================================================

    def __str__(self):

        return (
            f"{self.class_room.name} - "
            f"{self.subject.name}"
        )

    # ========================================================
    # META
    # ========================================================

    class Meta:

        ordering = [
            "class_room__name",
            "subject__name",
        ]

        constraints = [

            models.UniqueConstraint(
                fields=[
                    "class_room",
                    "subject",
                ],
                name="unique_class_subject",
            )

        ]

        verbose_name = "Class Subject"

        verbose_name_plural = "Class Subjects"

