# Generated by Django 6.0.6 on 2026-08-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login_attempt', 'Login Attempt'), ('login_success', 'Login Successfully'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('other', 'Other')], max_length=50),
        ),
    ]
